spring.application.name: station-configuration

spring.kafka.consumer:
  group-id: station-configuration-default
  auto-offset-reset: earliest

management:
  metrics.export.prometheus.enabled: true
  endpoint.env.enabled: true
  endpoints.web.exposure.include: "health,info,env,prometheus"
  metrics.tags.application: station_configuration

logging.config: "classpath:log4jconfig/log4j2.xml"

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      maximumPoolSize: 15
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

server:
  shutdown: graceful
  error:
    include-message: always
